### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shikulja** [fondlez/FonzAppraiser#1]
<img width="537" alt="image" src="https://github.com/fondlez/FonzAppraiser/assets/3386359/3f0def36-f568-4da7-836f-d076f4a8a0fd">

Hovering over the menu:
Pricing system
Notify -> (item-money-target) -> system

**Comment by fondlez** [comment]
The Ace addon libraries are no longer a dependency of the addon. Please update to the latest version of FonzAppraiser: https://github.com/fondlez/FonzAppraiser/releases/latest
